### ISSUE TITLE
Rentals Backup API

### ISSUE THREAD

**Issue by jamespeerless** [tcocca/you_got_listed#3]
Hey,

  Was wondering about adding support for the Rentals Backup endpoint (http://support.yougotlistings.com/knowledgebase/articles/224989-api-rentals-backup-csv-file-columns-definition).  The YGL documentation doesn't provide any information about where this endpoint is or how to use it.  Was hoping you might know.

Thanks

**Comment by tcocca** [comment]
Sorry, no idea.  Maybe its a CSV download somewhere in the interface (I can't tell you because I don't have access).  I'd email their support to ask about it.
